source 'https://rubygems.org'

gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'chefspec',   '~> 3.0'
gem 'foodcritic', '~> 3.0'
gem 'thor',       '~> 0.18'
gem 'strainer',   '~> 3.3'
gem 'chef',       '~> 11.0'
gem 'rspec',      '~> 2.14'
gem 'rubocop',    '~> 0.49'
